import type { Metadata } from "next";
import "./globals.css";
import LocalProvider from "@/provider/LocalProvider";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Ronie Benitez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LocalProvider>
          <main style={{ fontFamily: "Neue" }}>
            <Nav />
            {children}
            <Footer />
          </main>
        </LocalProvider>
      </body>
    </html>
  );
}
