import type { Metadata } from "next";
import "./globals.css";
import LocalProvider from "@/provider/LocalProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import CookieModal from "@/components/modal/cookie";
import ShareModal from "@/components/modal/sharer";
import Navbar from "@/components/layout/Navbar";
import Banner from "@/components/layout/Banner";
export const metadata: Metadata = {
  title: "Ronie Benitez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LocalProvider>
          <main
            className="flex flex-col p-0"
            style={{ fontFamily: "Mori, sans-serif" }}
          >
            <Banner />
            <Header />
            <Navbar />
            {children}
            <CookieModal />
            <Footer />
          </main>
        </LocalProvider>
      </body>
    </html>
  );
}
